export const menudata = [
  {
    id: 'core.file',
    label: '文件',
    iconClass: 'calendar',
    location: ['1_atu_file'],
    parentNode: true,
    order: '0',
    isEnabled: true,
    isShow: true,
    keybinding: '',
  },
  {
    id: 'core.edit',
    label: '编辑',
    iconClass: 'calendar',
    location: ['2_atu_edit'],
    hasSubmenu: true,
    order: '1',
    isEnabled: true,
    isShow: true,
    keybinding: '',
  },
  {
    id: 'core.project',
    label: '视图',
    iconClass: 'calendar',
    location: ['3_atu_view'],
    hasSubmenu: true,
    order: '2',
    isEnabled: true,
    isShow: true,
    keybinding: '',
  },
  {
    id: 'core.online.compile',
    label: '工程',
    iconClass: 'calendar',
    location: ['4_atu_project'],
    hasSubmenu: true,
    order: '3',
    isEnabled: true,
    isShow: true,
    keybinding: '',
  },
  {
    id: 'core.window',
    label: '编译',
    iconClass: 'calendar',
    location: ['5_atu_compile'],
    hasSubmenu: true,
    order: '4',
    isEnabled: true,
    isShow: true,
    keybinding: '',
  },
  {
    id: 'core.window',
    label: '在线',
    iconClass: 'calendar',
    location: ['6_atu_online'],
    hasSubmenu: true,
    order: '4',
    isEnabled: true,
    isShow: true,
    keybinding: '',
  },
  {
    id: 'core.window',
    label: '调试',
    iconClass: 'calendar',
    location: ['7_atu_debug'],
    hasSubmenu: true,
    order: '4',
    isEnabled: true,
    isShow: true,
    keybinding: '',
  },
  {
    id: 'core.window',
    label: '工具',
    iconClass: 'calendar',
    location: ['8_atu_tool'],
    hasSubmenu: true,
    order: '4',
    isEnabled: true,
    isShow: true,
    keybinding: '',
  },
  {
    id: 'core.help',
    label: '帮助',
    iconClass: 'calendar',
    location: ['9_atu_help'],
    hasSubmenu: true,
    order: '5',
    isEnabled: true,
    isShow: true,
    keybinding: '',
  },
];
